services:
  - type: web
    name: legamunity-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
